import type { Metadata } from "next";

import { Inter } from "next/font/google";
import { notFound } from "next/navigation";

import { hasLocale } from "next-intl";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import { Topbar } from "@/components/Topbar/Topbar";

import { routing } from "@/i18n/routing";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Js Boilerplate",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html className={inter.className} lang={locale} suppressHydrationWarning>
      <body
        className="flex h-screen flex-col font-light"
        suppressHydrationWarning
      >
        <NextIntlClientProvider messages={messages}>
          <Topbar />

          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
